name: CI Test Auth App


on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkoout code
        uses: actions/checkout@v2

    steps:
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

    steps:
      - name: Run tests
        run: pyton -m unittest discover



    